const mongoose = require('mongoose');

const PolicySchema = new mongoose.Schema({
    AdjustedPremium: Number,
    AnnualPremium: Number,
    AutoUwResultCode: String,
    BeforeVatPremium: Number,
    BusinessCateCode: String,
    BusinessObjectId: Number,
    DataEntryUserId: Number,
    DataEntryUserRealName: String,
    DuePremium: Number,
    EffectiveDate: Date,
    ExpiryDate: Date,
    FirstDataEntryDate: Date,
    GrossPremium: Number,
    IsPremiumCalcSuccess: String,
    IsRenewable: String,
    IsTakeUpPolicy: String,
    IssueDate: Date,
    IssueUserId: Number,
    IssueUserRealName: String,
    OrgCode: String,
    PlanType: String,
    PolicyCustomerList: [
        {
            Address: String,
            BusinessObjectId: Number,
            Email: String,
            IsInsured: String,
            IsOrgParty: String,
            IsPolicyHolder: String,
            Mobile: String,
            Occupation: String,
            ParentElementType: String,
            ParentPolicyElementId: Number,
            Phone: String,
            PolicyElementId: Number,
            PolicyId: Number,
            PolicyStatus: Number,
            ProposerName: String,
            SequenceNumber: Number,
            TempData: {
                "Mask-Mobile": String,
                Mobile: String,
                "MaskAfter-Mobile": String,
            },
        },
    ],
    PolicyElementId: Number,
    PolicyId: Number,
    PolicyLobList: [
        {
            AdjustedPremium: Number,
            AnnualPremium: Number,
            BeforeVatPremium: Number,
            BusinessObjectId: Number,
            GrossPremium: Number,
            ParentElementType: String,
            ParentPolicyElementId: Number,
            PolicyElementId: Number,
            PolicyId: Number,
            PolicyRiskList: [
                {
                    AdjustedPremium: Number,
                    AnnualPremium: Number,
                    BeforeVatPremium: Number,
                    BusinessObjectId: Number,
                    ChassisNo: String,
                    ClaimsDescription: String,
                    CommercialAdPaintVehicle: String,
                    DetailsOfAlteredVehicleSpec: String,
                    DiscountType: String,
                    DoYouHaveALoanOrFinanceOnThisVehicle: String,
                    DriverExperience: String,
                    DrivingLicenceType: String,
                    EngineCapacity: Number,
                    EngineNo: String,
                    GrossPremium: Number,
                    InConnectionOccupationBusiness: String,
                    InLast3YearsAnyLossesOrClaim: String,
                    IsVehiclePartAlteredFromOriginalSpec: String,
                    IsVehiclePurchaseWithTaxAllowance: String,
                    IsYourCarWellMaintained: String,
                    LicenseRevoked: String,
                    LicenseRevokedReason: String,
                    Make: String,
                    ManufactureDate: Date,
                    Model: String,
                    Other: String,
                    PaintingValue: Number,
                    ParentElementType: String,
                    ParentPolicyElementId: Number,
                    PlaceOfVehicleParkedAtNight: String,
                    PolicyCoverageList: [
                        {
                            BusinessObjectId: Number,
                            IsAutoAttachedForm: String,
                            IsFinalLevelCt: String,
                            ParentElementType: String,
                            ParentPolicyElementId: Number,
                            PolicyElementId: Number,
                            PolicyId: Number,
                            PolicyStatus: Number,
                            ProductElementCode: String,
                            ProductElementId: Number,
                            SequenceNumber: Number,
                        },
                    ],
                    PolicyElementId: Number,
                    PolicyId: Number,
                    PolicyStatus: Number,
                    PrevInsuranceList: [
                        {
                            BusinessObjectId: Number,
                            IsCurrentPolicyAvailable: String,
                            ParentElementType: String,
                            ParentPolicyElementId: Number,
                            PolicyElementId: Number,
                            PolicyId: Number,
                            PolicyStatus: Number,
                            PrevPolicyExpiryDate: Date,
                            PrevPolicyNCB: String,
                            PreviousPolicyInsuranceCompany: String,
                            SequenceNumber: Number,
                        },
                    ],
                    ProductElementCode: String,
                    ProductElementId: Number,
                    RegistrationNo: String,
                    SequenceNumber: Number,
                    SocialDomesticPleasure: String,
                    SumInsured: Number,
                    SumInsuredOption: Number,
                    VehicleDrivenBy: String,
                    VehicleParked: String,
                    VehicleUsed24Hrs: String,
                    WithinPhnomPenh: String,
                    WorkingHrsIncludeTravelToFromWork: String,
                },
            ],
            PolicyStatus: Number,
            ProductCode: String,
            ProductElementCode: String,
            ProductElementId: Number,
            ProductId: Number,
            ProductLobId: Number,
            SequenceNumber: Number,
            StandardGrossPremium: Number,
            SumInsured: Number,
            TechProductCode: String,
            TechProductId: Number,
        },
    ],
    PolicyNo: String,
    PolicyStatus: Number,
    PolicyType: String,
    PremCalcFactorHash: String,
    PremCalcResultHash: String,
    ProductCode: String,
    ProductId: Number,
    ProductVersion: String,
    ProposalDate: Date,
    ProposalNo: String,
    ProposalStatus: String,
    QuotationDate: Date,
    SchemaVersion: Number,
    StandardGrossPremium: Number,
    SumInsured: Number,
    TechProductCode: String,
    TechProductId: Number,
    VersionSeq: Number,
});

const Policy = mongoose.model('Policy', PolicySchema);

module.exports = Policy;
